# Generated by Django 4.2.1 on 2023-06-05 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_choice_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
