# Generated by Django 4.2.1 on 2023-06-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='is_correct_answer',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translated_correct_answer',
        ),
    ]
