# Generated by Django 4.2.1 on 2023-06-05 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_is_correct_choice_is_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translated_correct_answer',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
