# Generated by Django 4.2.1 on 2023-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_translation_translated_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='is_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
