# Generated by Django 4.2.1 on 2023-06-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_translation_is_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct_answer',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='is_correct_answer',
        ),
    ]
